### ISSUE TITLE
Suggestion: injectable IdentityOptions (instead of NistAccountOptions) 

### ISSUE THREAD

**Issue by pcbl** [brunohbrito/JPProject.Core#7]
Hello Folks,

I have one situation where we need to have not so "strong password" policies as defined on NistAccountOptions(). My suggestion would be that we make it "injectable", allowing people to override when it makes sense, or if we need to actually change the policies to make it even stronger...

Does that make sense?

Best Regards
Pedro

**Comment by brunobritodev** [comment]
Hi @pcbl ,

It makes! The next version I'll pull out the Database and Identity configuration from base classes. So It'll be less coupled, giving more flexibility.

**Comment by brunobritodev** [comment]
Hi,

Now it's possible to change Identity configuration, since it's not highly coupled with base classes!
